### ISSUE TITLE
empty mem locs between fontset & ROM

### ISSUE THREAD

**Issue by mooncell07** [mooncell07/Trace-Fractal#1]
According to the standards, first 512 memory locations are filled by the fonts and ROMs must start loading after 512th. 

The problem is,  the font set is not loading on entire 512 locations and the bytes of ROM are starting from 512. That is why a lot of memory locations are empty between the last byte of font set and first byte of ROM.

**Comment by NovaEmiya** [comment]
I researched a little and found out that, the original chip8 had an interpreter residing in these locations, though I am still confused on what to do with this empty space now.
